# Site settings
title: Erika Papp-Kovacs
subtitle: ""
description: "Focusing on legislation, practice and the gap between them."
baseurl: ""
url: "https://erikakovacs.github.io"
github_username: erikakovacs
author: Erika Papp-Kovacs

# Build settings
markdown: kramdown
permalink: pretty
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

include:
  - _pages

search: true

lunr:
  search_within_pages: true

atom_feed:
  hide: true

site:
  author: Erika Papp-Kovacs
